# Generated by Django 4.2.4 on 2023-08-29 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('ST', 'Standard'), ('DL', 'Deluxe'), ('SU', 'Suite'), ('FM', 'Family'), ('EX', 'Executive'), ('BD', 'Bridal'), ('PR', 'Presidential')], default='ST', max_length=2)),
                ('amenities', models.JSONField(default={'Air conditioning': True, 'Balcony': True, 'Private bathroom': True, 'bed': 2, 'capacity': 2, 'free wifi': True})),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isOccupied', models.BooleanField(default=False)),
                ('featured_image', models.ImageField(blank=True, upload_to='images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('rating', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=2)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
