# Generated by Django 4.2.4 on 2023-09-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_room_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='rating',
        ),
    ]
